### ISSUE TITLE
!badges command is not agnostic to the argument order

### ISSUE THREAD

**Issue by Felk** [TwitchPlaysPokemon/tpp-core#112]
The !badges command should work with both `!badges <user> <species>` and `!badges <species> <user>`.  
However, `!badges pidgey felkcraft` works, but `!badges felkcraft pidgey` gives the following error:

> No pokemon with the name 'felkcraft' was recognized. Please supply a valid name, or prefix with '#' to supply and pokedex number instead

**Comment by 6100m** [comment]
Going to try to fix this this week and the next :) I will DM you when I have made progress.

**Comment by Felk** [comment]
I want to clarify that this issue is still for grabs. 6100m won't fix this issue

**Comment by 6100m** [comment]
Indeed yeah. To help people a bit, the file is in Core/Commands/Definitions/BadgeCommands.cs, hope that helps people.
