### ISSUE TITLE
Hook up the new core to the new overlay

### ISSUE THREAD

**Issue by Felk** [TwitchPlaysPokemon/tpp-core#17]
The new overlay isn't open source (yet), so this is more of an internal tracking issue.

The details on how the new overlay should be hooked up to the new core (this one) are still very unclear. Since they are developed side-by-side, we should probably put effort into marrying them together soon, so the two developments don't drift apart.

**Comment by Felk** [comment]
https://github.com/TwitchPlaysPokemon/hud2 is barely a thing yet, so I've started interfacing with the old overlay

**Comment by m4-used-rollout** [comment]
https://github.com/TwitchPlaysPokemon/tppinputfeed comprises the new overlay now. This is already accomplished.
