### ISSUE TITLE
username changes are not reflected in "Name" field.

### ISSUE THREAD

**Issue by Felk** [TwitchPlaysPokemon/tpp-core#182]
I don't know how to fix that elegantly right now, but I don't want to forget:

Users have 3 names: the "simple name" (all-lowercase, used for irc), the "display name" (as delivered from twitch, may be arbitrary, e.g. japanese, korean, chinese etc.), and one field that is just "name". The last one is guaranteed to only differ from the simple name in capitalization and is meant to be used as the tpp internal display name, since we don't want to use twitch's display name.

Now if someone has a name change, the "name" field doesn't get changed. If their new simple name differs from their previous one, the "name" field should be updated too.

**Comment by m4-used-rollout** [comment]
This is resulting in a lot of deadnames when using new core for the input feed.

**Comment by Felk** [comment]
fixed by a4f6416f6387e0b9638001580c38cc34915e9af2
