### ISSUE TITLE
Upgrade to netcoreapp2.0 and netstandard2.0 

### ISSUE THREAD

**Issue by huderlem** [TwitchPlaysPokemon/tpp-core#19]
We will need to target .Net Standard 2.0 to use TwitchLib's upcoming netstandard 2.0 release.  We would have originally done this, but Rider didn't support .Net core 2.0 at the time we created the initial project.  (Rider support is coming soon. )

**Comment by Felk** [comment]
solved by 2fc85033f910409afa4eb2730b5fdbf02fa4e871
