### ISSUE TITLE
Add a hybrid mode that combines run mode and dual core mode

### ISSUE THREAD

**Issue by m4-used-rollout** [TwitchPlaysPokemon/tpp-core#317]
Not only is this for an eventual future when we may be running inputs out of new core while old core still provides some other old features, but it'll also be useful for running inputs during PBR to test the charity event setup.

**Comment by Felk** [comment]
I just tested, and runmode actually already works as expected when `ForwardUnprocessedMessages` is set to `true`. All unprocessed messages are forwarded to old core as usual.

Is this what you need? Should let you run inputs during old core matchmode just fine.

**Comment by m4-used-rollout** [comment]
Sure, as long as any match mode commands serviced by new core still work.

**Comment by Felk** [comment]
What do you mean by that? New core would run in run mode wouldn't it? What commands did you have in mind?
