### ISSUE TITLE
Command Aliases

### ISSUE THREAD

**Issue by m4-used-rollout** [TwitchPlaysPokemon/tpp-core#401]
Much like how we can add static responses through the !responses command, it would be great if we could add aliases through an !aliases command.

For instance, during dual runs we have `!left` and `!right`. It would be great if a moderator or operator could also add `!gold` and `!silver` (for example) that map to `!left` and `!right`. Basically, if a user used an aliased command `!gold`, the command parser would replace it with `!left` and run it back through the parser again.

the aliased commands should probably translate to an entire string to allow for parameters to be hardcoded, but then also pass the rest of the command string so extra parameters can be added. For instance, we could have a `!bestbadges` command that would map to `!dex complement-from-dupes` so a user could say `!bestbadges m4_used_rollout` to execute `!dex complement-from-dupes m4_used_rollout`

**Comment by Felk** [comment]
It's now fully addressed by #423
