### ISSUE TITLE
Subscription rewards aren't being given out

### ISSUE THREAD

**Issue by m4-used-rollout** [TwitchPlaysPokemon/tpp-core#428]
Ever since we switched to EventSub it seems that subscription events are not being seen by the core. Users are not getting the tokens they are owed from subscribing, resubscribing, or sending/receiving gift subscriptions.

**Comment by Felk** [comment]
https://github.com/TwitchPlaysPokemon/tpp-core/pull/415 is ready for testing

**Comment by m4-used-rollout** [comment]
Subscription rewards were fixed with #415 . Thanks!
